# Generated by Django 3.1.4 on 2021-03-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=127)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('otp', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OTP',
            },
        ),
        migrations.CreateModel(
            name='Project_add',
            fields=[
                ('pid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=700)),
                ('link', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='modules_add',
            fields=[
                ('task_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('task_desc', models.CharField(max_length=500)),
                ('task_status', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project_add')),
            ],
        ),
    ]
