# Generated by Django 3.1 on 2021-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=700)),
                ('link', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=300)),
            ],
        ),
    ]
