# Generated by Django 3.1.7 on 2021-03-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=700)),
                ('link', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
