# Generated by Django 3.1.7 on 2021-04-12 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_add",
            name="proj_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media/proj_image/"
            ),
            preserve_default=False,
        ),
    ]
